import { Translations, Language } from './types';
import {
  LayoutDashboard,
  Settings,
  List,
  Map as MapIcon,
  Server,
  Activity,
  Info,
  ShieldCheck
} from 'lucide-react';

export const TRANSLATIONS: Record<Language, Translations> = {
  ar: {
    dashboard: 'لوحة القيادة',
    map: 'الخريطة الحية',
    events: 'سجل الأحداث',
    sources: 'المصادر',
    status: 'حالة النظام',
    settings: 'الإعدادات',
    about: 'عن النظام',
    privacy: 'الخصوصية',
    language: 'اللغة',
    logout: 'تسجيل خروج',
    search_placeholder: 'بحث في النظام...',
    welcome_back: 'مركز العمليات',
    system_status: 'الحالة التشغيلية',
    active_threats: 'التهديدات النشطة',
    network_load: 'حمل الشبكة',
    recent_events: 'أحدث التنبيهات',
    view_all: 'عرض الكل',
    critical: 'حرج',
    high: 'عالي',
    medium: 'متوسط',
    low: 'منخفض',
    connected: 'متصل',
    disconnected: 'غير متصل',
    syncing: 'جاري المزامنة',
    error: 'خطأ',
    layers: 'الطبقات',
    filters: 'تصفية',
    live_feed: 'تغذية حية',
    new_alert: 'تنبيه جديد',
    notifications: 'الإشعارات',
    general: 'عام',
    display: 'العرض',
    save_changes: 'حفظ التغييرات',
    time_since_last_event: 'منذ آخر حدث',
    // Layers Panel
    layers_panel: 'لوحة الطبقات',
    categories: 'التصنيفات',
    time_range: 'المدى الزمني',
    severity: 'الخطورة',
    cat_conflicts: 'نزاعات',
    cat_protests: 'احتجاجات',
    cat_natural: 'كوارث طبيعية',
    cat_cyber: 'أمن سيبراني',
    cat_health: 'صحة',
    cat_terrorism: 'إرهاب',
    cat_infrastructure: 'بنية تحتية',
    time_1h: 'آخر ساعة',
    time_24h: '24 ساعة',
    time_7d: '7 أيام',
    time_all: 'الكل',
    // Event Details
    summary: 'الملخص',
    raw_payload: 'البيانات الخام',
    correlation_graph: 'رسم الترابط',
    visualizing_connections: 'تخيل الروابط لـ',
    metadata: 'البيانات الوصفية',
    detected_at: 'تم الكشف في',
    source_system: 'النظام المصدر',
    location: 'الموقع',
    tags: 'الوسوم',
    investigate: 'تحقيق',
    false_positive: 'تحديد كإنذار خاطئ',
    share: 'مشاركة',
    json: 'JSON',
    source_btn: 'المصدر',
    confidence: 'الثقة',
    loading_error: 'جاري التحميل أو لم يتم العثور على الحدث...',
  },
  en: {
    dashboard: 'Dashboard',
    map: 'Live Map',
    events: 'Events Feed',
    sources: 'Sources',
    status: 'System Status',
    settings: 'Settings',
    about: 'About',
    privacy: 'Privacy',
    language: 'Language',
    logout: 'Logout',
    search_placeholder: 'Search system...',
    welcome_back: 'Operations Center',
    system_status: 'Operational Status',
    active_threats: 'Active Threats',
    network_load: 'Network Load',
    recent_events: 'Latest Alerts',
    view_all: 'View All',
    critical: 'Critical',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    connected: 'Connected',
    disconnected: 'Disconnected',
    syncing: 'Syncing',
    error: 'Error',
    layers: 'Layers',
    filters: 'Filters',
    live_feed: 'Live Feed',
    new_alert: 'New Alert',
    notifications: 'Notifications',
    general: 'General',
    display: 'Display',
    save_changes: 'Save Changes',
    time_since_last_event: 'TIME SINCE LAST EVENT',
    // Layers Panel
    layers_panel: 'Layers Panel',
    categories: 'Categories',
    time_range: 'Time Range',
    severity: 'Severity',
    cat_conflicts: 'Conflicts',
    cat_protests: 'Protests',
    cat_natural: 'Natural Disasters',
    cat_cyber: 'Cyber Security',
    cat_health: 'Health',
    cat_terrorism: 'Terrorism',
    cat_infrastructure: 'Infrastructure',
    time_1h: 'Last Hour',
    time_24h: '24 Hours',
    time_7d: '7 Days',
    time_all: 'All Time',
    // Event Details
    summary: 'Summary',
    raw_payload: 'Raw Payload',
    correlation_graph: 'Correlation Graph',
    visualizing_connections: 'Visualizing connections for',
    metadata: 'Metadata',
    detected_at: 'Detected At',
    source_system: 'Source System',
    location: 'Location',
    tags: 'Tags',
    investigate: 'Investigate',
    false_positive: 'Mark as False Positive',
    share: 'Share',
    json: 'JSON',
    source_btn: 'Source',
    confidence: 'Confidence',
    loading_error: 'Loading or Event Not Found...',
  },
  de: {
    dashboard: 'Armaturenbrett',
    map: 'Live-Karte',
    events: 'Ereignisse',
    sources: 'Quellen',
    status: 'Systemstatus',
    settings: 'Einstellungen',
    about: 'Über',
    privacy: 'Datenschutz',
    language: 'Sprache',
    logout: 'Abmelden',
    search_placeholder: 'System durchsuchen...',
    welcome_back: 'Operationsbasis',
    system_status: 'Betriebsstatus',
    active_threats: 'Aktive Bedrohungen',
    network_load: 'Netzwerklast',
    recent_events: 'Neueste Warnungen',
    view_all: 'Alle ansehen',
    critical: 'Kritisch',
    high: 'Hoch',
    medium: 'Mittel',
    low: 'Niedrig',
    connected: 'Verbunden',
    disconnected: 'Getrennt',
    syncing: 'Synchronisieren',
    error: 'Fehler',
    layers: 'Ebenen',
    filters: 'Filter',
    live_feed: 'Live-Feed',
    new_alert: 'Neue Warnung',
    notifications: 'Benachrichtigungen',
    general: 'Allgemein',
    display: 'Anzeige',
    save_changes: 'Änderungen speichern',
    time_since_last_event: 'ZEIT SEIT LETZTEM EREIGNIS',
    // Layers Panel
    layers_panel: 'Ebenen',
    categories: 'Kategorien',
    time_range: 'Zeitraum',
    severity: 'Schweregrad',
    cat_conflicts: 'Konflikte',
    cat_protests: 'Proteste',
    cat_natural: 'Naturkatastrophen',
    cat_cyber: 'Cyber-Sicherheit',
    cat_health: 'Gesundheit',
    cat_terrorism: 'Terrorismus',
    cat_infrastructure: 'Infrastruktur',
    time_1h: 'Letzte Stunde',
    time_24h: '24 Stunden',
    time_7d: '7 Tage',
    time_all: 'Gesamt',
    // Event Details
    summary: 'Zusammenfassung',
    raw_payload: 'Rohdaten',
    correlation_graph: 'Korrelationsdiagramm',
    visualizing_connections: 'Verbindungen visualisieren für',
    metadata: 'Metadaten',
    detected_at: 'Erkannt am',
    source_system: 'Quellsystem',
    location: 'Standort',
    tags: 'Tags',
    investigate: 'Untersuchen',
    false_positive: 'Als Fehlalarm markieren',
    share: 'Teilen',
    json: 'JSON',
    source_btn: 'Quelle',
    confidence: 'Vertrauen',
    loading_error: 'Laden oder Ereignis nicht gefunden...',
  }
};

export const NAVIGATION_ITEMS = [
  { id: 'map', icon: MapIcon, path: '/map' },
  { id: 'events', icon: List, path: '/events' },
  { id: 'sources', icon: Server, path: '/sources' },
  { id: 'status', icon: Activity, path: '/status' },
  { id: 'settings', icon: Settings, path: '/settings' },
  { id: 'about', icon: Info, path: '/about' },
];

export const COUNTRY_TRANSLATIONS: Record<string, Record<Language, string>> = {
  'USA': { ar: 'الولايات المتحدة', en: 'USA', de: 'USA' },
  'Germany': { ar: 'ألمانيا', en: 'Germany', de: 'Deutschland' },
  'Ukraine': { ar: 'أوكرانيا', en: 'Ukraine', de: 'Ukraine' },
  'Yemen': { ar: 'اليمن', en: 'Yemen', de: 'Jemen' },
  'Taiwan': { ar: 'تايوان', en: 'Taiwan', de: 'Taiwan' },
  'Iran': { ar: 'إيران', en: 'Iran', de: 'Iran' },
  'China': { ar: 'الصين', en: 'China', de: 'China' },
  'North Korea': { ar: 'كوريا الشمالية', en: 'North Korea', de: 'Nordkorea' },
  'Russia': { ar: 'روسيا', en: 'Russia', de: 'Russland' },
  'Syria': { ar: 'سوريا', en: 'Syria', de: 'Syrien' },
  'Iraq': { ar: 'العراق', en: 'Iraq', de: 'Irak' },
  'Lebanon': { ar: 'لبنان', en: 'Lebanon', de: 'Libanon' },
  'France': { ar: 'فرنسا', en: 'France', de: 'Frankreich' },
  'UK': { ar: 'المملكة المتحدة', en: 'UK', de: 'Vereinigtes Königreich' },
  'Japan': { ar: 'اليابان', en: 'Japan', de: 'Japan' },
  'South Korea': { ar: 'كوريا الجنوبية', en: 'South Korea', de: 'Südkorea' },
  'Hawaii': { ar: 'هاواي', en: 'Hawaii', de: 'Hawaii' },
  'California': { ar: 'كاليفورنيا', en: 'California', de: 'Kalifornien' },
  'Chile': { ar: 'تشيلي', en: 'Chile', de: 'Chile' },
  'Puerto Rico': { ar: 'بورتوريكو', en: 'Puerto Rico', de: 'Puerto Rico' },
  'Alaska': { ar: 'ألاسكا', en: 'Alaska', de: 'Alaska' },
  'Australia': { ar: 'أستراليا', en: 'Australia', de: 'Australien' },
  'Canada': { ar: 'كندا', en: 'Canada', de: 'Kanada' },
  'Mexico': { ar: 'المكسيك', en: 'Mexico', de: 'Mexiko' },
  'Brazil': { ar: 'البرازيل', en: 'Brazil', de: 'Brasilien' },
  'Egypt': { ar: 'مصر', en: 'Egypt', de: 'Ägypten' },
  'Saudi Arabia': { ar: 'السعودية', en: 'Saudi Arabia', de: 'Saudi-Arabien' },
  'UAE': { ar: 'الإمارات', en: 'UAE', de: 'VAE' },
  'Turkey': { ar: 'تركيا', en: 'Turkey', de: 'Türkei' },
  'Italy': { ar: 'إيطاليا', en: 'Italy', de: 'Italien' },
  'Spain': { ar: 'إسبانيا', en: 'Spain', de: 'Spanien' },
  'Oklahoma': { ar: 'أوكلاهوما', en: 'Oklahoma', de: 'Oklahoma' },
  'Portugal': { ar: 'البرتغال', en: 'Portugal', de: 'Portugal' },
  'Indonesia': { ar: 'إندونيسيا', en: 'Indonesia', de: 'Indonesien' },
  'Philippines': { ar: 'الفلبين', en: 'Philippines', de: 'Philippinen' },
  'Papua New Guinea': { ar: 'بابوا غينيا الجديدة', en: 'Papua New Guinea', de: 'Papua-Neuguinea' },
  'Fiji': { ar: 'فيجي', en: 'Fiji', de: 'Fidschi' },
  'Tonga': { ar: 'تونغا', en: 'Tonga', de: 'Tonga' },
  'New Zealand': { ar: 'نيوزيلندا', en: 'New Zealand', de: 'Neuseeland' },
  'Vanuatu': { ar: 'فانواتو', en: 'Vanuatu', de: 'Vanuatu' },
  'Solomon Islands': { ar: 'جزر سليمان', en: 'Solomon Islands', de: 'Salomonen' },
  'DE': { ar: 'ألمانيا', en: 'Germany', de: 'Deutschland' },
  'FR': { ar: 'فرنسا', en: 'France', de: 'Frankreich' },
  'US': { ar: 'الولايات المتحدة', en: 'USA', de: 'USA' },
  'RU': { ar: 'روسيا', en: 'Russia', de: 'Russland' },
  'CN': { ar: 'الصين', en: 'China', de: 'China' },
  'IN': { ar: 'الهند', en: 'India', de: 'Indien' },
  'IR': { ar: 'إيران', en: 'Iran', de: 'Iran' },
  'IQ': { ar: 'العراق', en: 'Iraq', de: 'Irak' },
  'SY': { ar: 'سوريا', en: 'Syria', de: 'Syrien' },
  'JP': { ar: 'اليابان', en: 'Japan', de: 'Japan' },
  'KR': { ar: 'كوريا الجنوبية', en: 'South Korea', de: 'Südkorea' },
  'CA': { ar: 'كاليفورنيا', en: 'California', de: 'Kalifornien' },
  'MX': { ar: 'المكسيك', en: 'Mexico', de: 'Mexiko' },
  'BR': { ar: 'البرازيل', en: 'Brazil', de: 'Brasilien' },
  'AU': { ar: 'أستراليا', en: 'Australia', de: 'Australien' },
  'EG': { ar: 'مصر', en: 'Egypt', de: 'Ägypten' },
  'SA': { ar: 'السعودية', en: 'Saudi Arabia', de: 'Saudi-Arabien' },
  'AE': { ar: 'الإمارات', en: 'UAE', de: 'VAE' },
  'GB': { ar: 'المملكة المتحدة', en: 'UK', de: 'Vereinigtes Königreich' },
  'ES': { ar: 'إسبانيا', en: 'Spain', de: 'Spanien' },
  'IT': { ar: 'إيطاليا', en: 'Italy', de: 'Italien' },
  'TR': { ar: 'تركيا', en: 'Turkey', de: 'Türkei' },
  'PT': { ar: 'البرتغال', en: 'Portugal', de: 'Portugal' },
  // US States (for USGS earthquake data)
  'Washington': { ar: 'واشنطن', en: 'Washington', de: 'Washington' },
  'Nevada': { ar: 'نيفادا', en: 'Nevada', de: 'Nevada' },
  'Montana': { ar: 'مونتانا', en: 'Montana', de: 'Montana' },
  'Tennessee': { ar: 'تينيسي', en: 'Tennessee', de: 'Tennessee' },
  'Utah': { ar: 'يوتا', en: 'Utah', de: 'Utah' },
  'Oregon': { ar: 'أوريغون', en: 'Oregon', de: 'Oregon' },
  'Idaho': { ar: 'أيداهو', en: 'Idaho', de: 'Idaho' },
  'Wyoming': { ar: 'وايومنغ', en: 'Wyoming', de: 'Wyoming' },
  'Texas': { ar: 'تكساس', en: 'Texas', de: 'Texas' },
  'Kansas': { ar: 'كانساس', en: 'Kansas', de: 'Kansas' },
  'Arkansas': { ar: 'أركنساس', en: 'Arkansas', de: 'Arkansas' },
  'North Carolina': { ar: 'كارولينا الشمالية', en: 'North Carolina', de: 'North Carolina' },
  'South Carolina': { ar: 'كارولينا الجنوبية', en: 'South Carolina', de: 'South Carolina' },
  'Missouri': { ar: 'ميسوري', en: 'Missouri', de: 'Missouri' },
  'Colorado': { ar: 'كولورادو', en: 'Colorado', de: 'Colorado' },
  'New Mexico': { ar: 'نيو مكسيكو', en: 'New Mexico', de: 'New Mexico' },
  'Arizona': { ar: 'أريزونا', en: 'Arizona', de: 'Arizona' },
  'Nebraska': { ar: 'نبراسكا', en: 'Nebraska', de: 'Nebraska' },
  'Virginia': { ar: 'فرجينيا', en: 'Virginia', de: 'Virginia' },
  'West Virginia': { ar: 'فرجينيا الغربية', en: 'West Virginia', de: 'West Virginia' },
  // Countries (not already defined above)
  'Afghanistan': { ar: 'أفغانستان', en: 'Afghanistan', de: 'Afghanistan' },
  'Pakistan': { ar: 'باكستان', en: 'Pakistan', de: 'Pakistan' },
  'Greece': { ar: 'اليونان', en: 'Greece', de: 'Griechenland' },
  'Colombia': { ar: 'كولومبيا', en: 'Colombia', de: 'Kolumbien' },
  'Argentina': { ar: 'الأرجنتين', en: 'Argentina', de: 'Argentinien' },
  'Peru': { ar: 'بيرو', en: 'Peru', de: 'Peru' },
  'Ecuador': { ar: 'الإكوادور', en: 'Ecuador', de: 'Ecuador' },
  'Venezuela': { ar: 'فنزويلا', en: 'Venezuela', de: 'Venezuela' },
  'Thailand': { ar: 'تايلاند', en: 'Thailand', de: 'Thailand' },
  'Myanmar': { ar: 'ميانمار', en: 'Myanmar', de: 'Myanmar' },
  'Nepal': { ar: 'نيبال', en: 'Nepal', de: 'Nepal' },
  // Mock location names
  'Madrid': { ar: 'مدريد', en: 'Madrid', de: 'Madrid' },
  'Remote Outpost': { ar: 'موقع نائي', en: 'Remote Outpost', de: 'Außenposten' },
};