

export type Language = 'ar' | 'en' | 'de';
export type Direction = 'rtl' | 'ltr';

export interface User {
  id: string;
  name: string;
  role: 'admin' | 'user';
  avatar: string;
}

export interface Metric {
  id: string;
  label: string;
  value: string | number;
  change: number;
  trend: 'up' | 'down' | 'neutral';
}

// Infrastructure Assets
export type AssetType = 'power_plant' | 'substation' | 'telecom_tower' | 'data_center' | 'airport' | 'seaport' | 'railway' | 'submarine_cable' | 'vessel';

export interface Asset {
  id: string;
  type: AssetType;
  name: string;
  location: {
    lat: number;
    lon: number;
  };
  details?: Record<string, any>; // Flexible for varying OSM tags
  distance?: number; // Distance from a reference event in km
  risk_score?: number; // 0-100 calculated risk
}

// Fusion & Risk Analysis Types
export interface ImpactedAsset extends Asset {
  impact_type: 'direct_hit' | 'shockwave' | 'disruption_zone' | 'cascading';
  estimated_damage: string; // Text description for now
}

export interface RiskAnalysis {
  score: number; // 0-100 Global Risk Score
  level: 'critical' | 'high' | 'medium' | 'low';
  impacted_assets: ImpactedAsset[];
  recommendation: string;
  timestamp: string;
  weather_context?: {
    temp_c: number;
    wind_kph: number;
    condition: string;
  };
  // Phase 4: Mathematical Breakdown
  factors?: {
    threat_score: number; // 0-1 Normalized Threat Magnitude
    consequence_score: number; // 0-1 Aggregate Potential Loss
    vulnerability_score: number; // 0-1 Average Asset Vulnerability
  };
}

// Normalized Event Schema
export interface UnifiedEvent {
  id: string;
  source: string;      // e.g., 'firewall-01', 'twitter', 'rss_feed'
  category: string;    // e.g., 'network', 'social', 'malware', 'geopolitical'
  severity: 'critical' | 'high' | 'medium' | 'low';
  confidence: number;  // 0.0 to 1.0
  title: string;       // Short headline
  summary: string;     // Detailed description
  time: string;        // ISO 8601 Date String
  lat?: number;        // Latitude
  lon?: number;        // Longitude
  country?: string;
  region?: string;
  tags: string[];
  url?: string;        // Link to original source
  rawPayload?: any;    // Original raw JSON/Object
  analysis?: RiskAnalysis; // Pre-calculated risk analysis

  // Translation
  translated?: {
    title: string;
    summary: string;
    lang: string;
  };

  // Phase 6: AI Cognitive Insights
  ai_insights?: {
    summary?: string; // Generated by LLM
    sentiment?: {
      score: number;
      label: 'positive' | 'negative' | 'neutral';
    };
    detected_objects?: string[]; // Vision results (e.g. ['tank', 'ship'])
    audio_transcript?: string; // STT results
  };
}

export interface DataSource {
  id: string;
  name: string;
  type: 'api' | 'rss' | 'social' | 'sensor';
  status: 'connected' | 'disconnected' | 'error' | 'syncing';
  lastSync: string;
  eventCount: number;
}

// Design System Types
export type ToastType = 'success' | 'error' | 'info' | 'warning';

export interface ToastMessage {
  id: string;
  type: ToastType;
  title?: string;
  message: string;
  duration?: number;
}

export interface NotificationPreferences {
  enabled: boolean;
  channels: {
    push: boolean;
    email: boolean;
    sms: boolean;
  };
  filters: {
    severities: Record<string, boolean>; // critical, high, medium, low
    categories: Record<string, boolean>; // conflicts, natural, etc.
    regions: string[]; // e.g. "Europe", "Middle East"
  };
  pushConfig: {
    permissionStatus: NotificationPermission | 'default';
    token: string | null;
  };
}

export interface Translations {
  [key: string]: string;
}
